development:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_development
  pool: 5
  host: localhost
  username: biblioteca
  password: biblioteca

production:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_production
  pool: 5
  host: localhost
  username: biblioteca
  password: biblioteca
