development:
  adapter: postgresql
  encoding: unicode
  database: sigproext_development
  pool: 5
  host: localhost
  username: sigproext
  password: sigproext

production:
  adapter: postgresql
  encoding: unicode
  database: sigproext_production
  pool: 5
  host: localhost
  username: sigproext
  password: sigproext
